# Generated by Django 5.2 on 2025-04-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_chatmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sender',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
